const express = require('express');
const meetingsRouter = express.Router();

const {
	getAllFromDatabase,
	addToDatabase,
	deleteAllFromDatabase,
	createMeeting,
} = require('./db');

// /api/meetings routes
// GET /api/meetings
// get an array of all meetings in the database
meetingsRouter.get('/', (req, res, next) => {
	// Return all meeting objects currently stored in memory.
	const meetings = getAllFromDatabase('meetings');
	res.send(meetings);
});

// POST /api/meetings
// create a meeting automatically and save it to the database
meetingsRouter.post('/', (req, res, next) => {
	try {
		// Meetings are generated by server logic, not by request body input.
		const newMeeting = createMeeting();
		// Persist the generated meeting object in the meetings collection.
		const addedMeeting = addToDatabase('meetings', newMeeting);
		if (!addedMeeting) {
			return res.status(400).send();
		}
		// Return the saved meeting with a created status.
		return res.status(201).send(addedMeeting);
	} catch (error) {
		// Validation problems become 400 responses.
		return res.status(400).send();
	}
});

// DELETE /api/meetings
// delete all meetings from the database
meetingsRouter.delete('/', (req, res, next) => {
	// Clear the entire meetings collection at once.
	deleteAllFromDatabase('meetings');
	// 204 indicates successful deletion without response body.
	res.status(204).send();
});

module.exports = meetingsRouter;
